{{- if .Values.bridges.alertmanager.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "matrix.fullname" . }}-bridge-alertmanager
  labels:
{{ include "matrix.labels" . | indent 4 }}
spec:
  revisionHistoryLimit: {{ .Values.bridges.alertmanager.revisionHistoryLimit }}
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "matrix.name" . }}-bridge-alertmanager
      app.kubernetes.io/instance: {{ .Release.Name }}
      matrix-chart/allow-synapse-access: allow
  template:
    metadata:
      annotations:
        # re-roll deployment on config change
        checksum/alertmanager-registration: {{ include (print $.Template.BasePath "/bridge-alertmanager/secret-registration.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "matrix.name" . }}-bridge-alertmanager
        app.kubernetes.io/instance: {{ .Release.Name }}
        matrix-chart/allow-synapse-access: allow
    spec:
      {{- if .Values.bridges.affinity }}
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - {{ include "matrix.name" . }}-synapse
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - {{ .Release.Name }}
              topologyKey: kubernetes.io/hostname
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.bridges.alertmanager.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: load-config
          image: "alpine:latest"
          imagePullPolicy: {{ .Values.bridges.alertmanager.image.pullPolicy }}
          command:
           - "/bin/sh"
           - "-c"
           - |
             cp /data/registration.yaml /bridges/alertmanager.yaml
          volumeMounts:
            - name: data
              mountPath: /data
            - name: bridges
              mountPath: /bridges
          {{- with .Values.bridges.alertmanager.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      containers:
        - name: "bridge-alertmanager"
          image: "{{ .Values.bridges.alertmanager.image.repository }}:{{ .Values.bridges.alertmanager.image.tag }}"
          imagePullPolicy: {{ .Values.bridges.alertmanager.image.pullPolicy }}
          env:
            - name: APP_PORT
              value: {{ .Values.bridges.alertmanager.config.app_port | quote }}

            - name: APP_ALERTMANAGER_SECRET
              value: {{ .Values.bridges.alertmanager.config.app_alertmanager_secret | default "matrix.alertmanager.webhook_secret" }}

            - name: MATRIX_HOMESERVER_URL
              value: {{ .Values.bridges.alertmanager.config.matrix_homeserver_url | default (include "matrix.baseUrl" .) }}

            - name: MATRIX_ROOMS
              value: {{ .Values.bridges.alertmanager.config.matrix_rooms }}

            - name: MATRIX_TOKEN
              value: {{ include "matrix.alertmanager.as_token" . }}

            - name: MATRIX_USER
              value: "@{{ .Values.bridges.alertmanager.config.matrix_user }}:{{ .Values.matrix.serverName }}"

            - name: MENTION_ROOM
              value: {{ .Values.bridges.alertmanager.config.mention_room | quote }}

            {{- if .Values.bridges.alertmanager.config.grafana_url }}
            - name: GRAFANA_URL
              value: {{ .Values.bridges.alertmanager.config.grafana_url }}

            - name: GRAFANA_DATASOURCE
              value: {{ .Values.bridges.alertmanager.config.grafana_datasource }}
            {{- end }}

            {{- if .Values.bridges.alertmanager.config.alertmanager_url }}
            - name: ALERTMANAGER_URL
              value: {{ .Values.bridges.alertmanager.config.alertmanager_url }}
            {{- end }}
          ports:
            - name: appservice
              containerPort: {{ .Values.bridges.alertmanager.config.app_port }}
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
           {{- with .Values.bridges.alertmanager.extraVolumeMounts }}
             {{- toYaml . | nindent 12 }}
           {{- end }}
          {{- with .Values.bridges.alertmanager.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.bridges.alertmanager.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: data
          projected:
            sources:
              - secret:
                  name: {{ include "matrix.alertmanager.registrationSecret" . }}
        - name: bridges
          persistentVolumeClaim:
            {{- if not .Values.bridges.volume.existingClaim }}
            claimName: "{{ include "matrix.fullname" . }}-bridges"
            {{- else -}}
            claimName: {{ .Values.bridges.volume.existingClaim }}
            {{- end }}
        {{- with .Values.bridges.alertmanager.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
