{{- if .Values.coturn.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "matrix.fullname" . }}-coturn
  labels:
{{ include "matrix.labels" . | indent 4 }}
{{ include "matrix.coturn.labels" . | indent 4}}
spec:
  type: {{ .Values.coturn.service.type }}
  ports:
    - port: 3478
      targetPort: turn-3478
      {{- if eq .Values.coturn.service.type "NodePort" }}
      nodePort: 3478
      {{- end }}
      protocol: UDP
      name: turn-3478
  selector:
    app.kubernetes.io/name: {{ include "matrix.name" . }}-coturn
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
