{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "matrix.fullname" . }}-postgresql-initdb
  labels:
  {{ include "matrix.labels" . | nindent 4}}
data:
  matrix.sql: |
    ALTER DATABASE {{ .Values.postgresql.global.postgresql.auth.database }} OWNER TO {{ .Values.postgresql.global.postgresql.auth.username }};
    GRANT ALL PRIVILEGES ON DATABASE {{ .Values.postgresql.global.postgresql.auth.database }} TO {{ .Values.postgresql.global.postgresql.auth.username }};
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO {{ .Values.postgresql.global.postgresql.auth.username }};
  {{- if .Values.bridges.irc.enabled }}
  {{/* Scripts are run in alphabetical order */}}
  zzz_irc.sql: |
    CREATE DATABASE {{ .Values.bridges.irc.database }}
       ENCODING 'UTF8'
       LC_COLLATE='C'
       LC_CTYPE='C'
       template=template0
       OWNER {{ .Values.postgresql.global.postgresql.auth.username }};
  {{- end }}
{{- end }}
