{{- if .Values.bridges.hookshot.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "matrix.fullname" . }}-hookshot-config
  labels:
  {{ include "matrix.labels" . | nindent 4}}
data:
  config.yaml: |
    # This is an example configuration file
    bridge:
      # Basic homeserver configuration
      domain: {{ .Values.matrix.serverName }}
      # url: http://localhost:8008
      url: "{{ include "matrix.baseUrl" . }}"
      # mediaUrl: https://example.com
      port: 9993
      bindAddress: 127.0.0.1
    passFile:
      # A passkey used to encrypt tokens stored inside the bridge.
      # Run openssl genpkey -out passkey.pem -outform PEM -algorithm RSA -pkeyopt rsa_keygen_bits:4096 to generate
      ./passkey.pem
    logging:
      # Logging settings. You can have a severity debug,info,warn,error
      level: info
      colorize: true
      json: false
      timestampFormat: HH:mm:ss:SSS
    listeners:
      # HTTP Listener configuration.
      # Bind resource endpoints to ports and addresses.
      # 'port' must be specified. Each listener must listen on a unique port.
      # 'bindAddress' will default to '127.0.0.1' if not specified, which may not be suited to Docker environments.
      # 'resources' may be any of webhooks, widgets, metrics, provisioning
      - port: 9000
        bindAddress: 0.0.0.0
        resources:
          - webhooks
      - port: 9001
        bindAddress: 127.0.0.1
        resources:
          - metrics
          - provisioning
      - port: 9002
        bindAddress: 0.0.0.0
        resources:
          - widgets

    #github:
    #  # (Optional) Configure this to enable GitHub support
    #  auth:
    #    # Authentication for the GitHub App.
    #    id: 123
    #    privateKeyFile: github-key.pem
    #  webhook:
    #    # Webhook settings for the GitHub app.
    #    secret: secrettoken
    #  oauth:
    #    # (Optional) Settings for allowing users to sign in via OAuth.
    #    client_id: foo
    #    client_secret: bar
    #    redirect_uri: https://example.com/oauth/
    #  defaultOptions:
    #    # (Optional) Default options for GitHub connections.
    #    showIssueRoomLink: false
    #    hotlinkIssues:
    #      prefix: "#"
    #  userIdPrefix:
    #    # (Optional) Prefix used when creating ghost users for GitHub accounts.
    #    _github_

    #gitlab:
    #  # (Optional) Configure this to enable GitLab support
    #  instances:
    #    gitlab.com:
    #      url: https://gitlab.com
    #  webhook:
    #    secret: secrettoken
    #    publicUrl: https://example.com/hookshot/
    #  userIdPrefix:
    #    # (Optional) Prefix used when creating ghost users for GitLab accounts.
    #    _gitlab_
    #  commentDebounceMs:
    #    # (Optional) Aggregate comments by waiting this many miliseconds before posting them to Matrix. Defaults to 5000 (5 seconds)
    #    5000

    #generic:
    #  # (Optional) Support for generic webhook events.
    #  #'allowJsTransformationFunctions' will allow users to write short transformation snippets in code, and thus is unsafe in untrusted environments

    #  enabled: false
    #  outbound: false
    #  enableHttpGet: false
    #  urlPrefix: https://example.com/webhook/
    #  userIdPrefix: _webhooks_
    #  allowJsTransformationFunctions: false
    #  waitForComplete: false

    #feeds:
    #  # (Optional) Configure this to enable RSS/Atom feed support
    #  enabled: false
    #  pollConcurrency: 4
    #  pollIntervalSeconds: 600
    #  pollTimeoutSeconds: 30

    #provisioning:
    #  # (Optional) Provisioning API for integration managers
    #  secret: "!secretToken"

    #bot:
    #  # (Optional) Define profile information for the bot user
    #  displayname: Hookshot Bot
    #  avatar: mxc://half-shot.uk/2876e89ccade4cb615e210c458e2a7a6883fe17d

    #serviceBots:
    #  # (Optional) Define additional bot users for specific services
    #  - localpart: feeds
    #    displayname: Feeds
    #    avatar: ./assets/feeds_avatar.png
    #    prefix: "!feeds"
    #    service: feeds

    #metrics:
    #  # (Optional) Prometheus metrics support
    #  enabled: true

    #cache:
    #  # (Optional) Cache options for large scale deployments.
    #  #    For encryption to work, this must be configured.
    #  redisUri: redis://localhost:6379

    #queue:
    #  # (Optional) Message queue configuration options for large scale deployments.
    #  # For encryption to work, this must not be configured.
    #  redisUri: redis://localhost:6379

    #sentry:
    #  # (Optional) Configure Sentry error reporting
    #  dsn: https://examplePublicKey@o0.ingest.sentry.io/0
    #  environment: production

    #permissions:
    #  # (Optional) Permissions for using the bridge. See docs/setup.md#permissions for help
    #  - actor: example.com
    #    services:
    #      - service: "*"
    #        level: admin

  registration.yaml: |
    id: appservice-hookshot
    namespaces:
      users:
        - exclusive: true
          regex: "@webook_.+:{{ .Values.matrix.serverName }}"
{{- end }}
