{{- if .Values.bridges.hookshot.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "matrix.fullname" . }}-bridge-hookshot
  labels:
{{ include "matrix.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.bridges.hookshot.replicaCount }}
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "matrix.name" . }}-bridge-hookshot
      app.kubernetes.io/instance: {{ .Release.Name }}
      matrix-chart/allow-synapse-access: allow
  template:
    metadata:
      {{- if not .Values.bridges.hookshot.existingSecret.config }}
      annotations:
        # re-roll deployment on config change
        checksum/hookshot-config: {{ include (print $.Template.BasePath "/bridge-hookshot/configmap.yaml") . | sha256sum }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "matrix.name" . }}-bridge-hookshot
        app.kubernetes.io/instance: {{ .Release.Name }}
        matrix-chart/allow-synapse-access: allow
    spec:
      {{- if .Values.bridges.affinity }}
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - {{ include "matrix.name" . }}-synapse
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - {{ .Release.Name }}
              topologyKey: kubernetes.io/hostname
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.bridges.hookshot.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: "load-config"
          image: "{{ .Values.bridges.hookshot.image.repository }}:{{ .Values.bridges.hookshot.image.tag }}"
          imagePullPolicy: {{ .Values.bridges.hookshot.image.pullPolicy }}
          command: ["sh"]
          args: ["-c", "cp /data/registration.yaml /bridges/hookshot.yaml"]
          volumeMounts:
            - name: data
              mountPath: /data
            - name: bridges
              mountPath: /bridges
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
      containers:
        - name: "bridge-hookshot"
          image: "{{ .Values.bridges.hookshot.image.repository }}:{{ .Values.bridges.hookshot.image.tag }}"
          imagePullPolicy: {{ .Values.bridges.hookshot.image.pullPolicy }}
          ports:
            - name: bridge
              containerPort: 9005
              protocol: TCP
            - name: webhook
              containerPort: {{ .Values.bridges.hookshot.service.webhook }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.bridges.hookshot.service.metrics }}
              protocol: TCP
            - name: appservice
              containerPort: {{ .Values.bridges.hookshot.service.appservice }}
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          {{- with .Values.bridges.hookshot.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: data
          projected:
            sources:
              {{- if not .Values.bridges.hookshot.existingSecret.config }}
              configMap:
                name: {{ include "matrix.hookshot.configmap" . }}
              {{- else -}}
              secret:
                secretName: {{ include "matrix.hookshot.configSecret" . }}
              {{- end }}
              secret:
                secretName: {{ include "matrix.hookshot.passkeySecret" . }}
              secret:
                secretName: {{ include "matrix.hookshot.registrationSecret" . }}
        - name: bridges
          persistentVolumeClaim:
            claimName: "{{ include "matrix.fullname" . }}-bridges"
{{- end }}
