{{- if and .Values.bridges.hookshot.enabled (not .Values.bridges.hookshot.existingSecret.passkey) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matrix.hookshot.passkeySecret" . }}
  labels:
  {{ include "matrix.labels" . | nindent 4}}
data:
  passkey.pem: {{ .Values.bridges.hookshot.passkey | b64enc | quote }}
{{- end }}
