{{- if and (not .Values.bridges.hookshot.existingSecret.registration) .Values.bridges.hookshot.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matrix.hookshot.registrationSecret" . }}
  labels:
  {{ include "matrix.labels" . | nindent 4}}
stringData:
  registration.yaml: |-
    id: appservice-hookshot
    namespaces:
      users:
        - exclusive: true
          regex: "@webook_.+:{{ .Values.matrix.serverName }}"
{{- end }}
