{{- if and (not .Values.bridges.hookshot.existingSecret.registration) .Values.bridges.hookshot.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matrix.hookshot.registrationSecret" . }}
  labels:
  {{ include "matrix.labels" . | nindent 4}}
stringData:
  registration.yml: |-
    id: appservice-hookshot
    as_token: "{{ include "matrix.hookshot.as_token" . }}"
    hs_token: "{{ include "matrix.hookshot.hs_token" . }}"
    namespaces:
      users:
        {{ if .Values.bridges.hookshot.config.generic.enabled }}
        - exclusive: true
          {{ if .Values.bridges.hookshot.config.generic.userIdPrefix }}
          regex: "@{{ .Values.bridges.hookshot.config.generic.userIdPrefix }}.+:{{ .Values.matrix.serverName }}"
          {{- else -}}
          regex: "@.+:{{ .Values.matrix.serverName }}"
          {{- end }}
        {{- end }}
        {{ if .Values.bridges.hookshot.config.github.enabled }}
        - exclusive: true
          {{ if .Values.bridges.hookshot.config.github.userIdPrefix }}
          regex: "@{{ .Values.bridges.hookshot.config.git.userIdPrefix }}.+:{{ .Values.matrix.serverName }}"
          {{- else -}}
          regex: "@.+:{{ .Values.matrix.serverName }}"
          {{- end }}
        {{- end }}
    url: "http://{{ include "matrix.fullname" . }}-bridge-hookshot:{{ .Values.bridges.hookshot.service.appservice.port }}"
    sender_localpart: _hookshot_bot
    rate_limited: false
    protocols:
      - hookshot
{{- end }}
