{{- if and (not .Values.bridges.hookshot.existingSecret.registration) .Values.bridges.hookshot.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matrix.hookshot.registrationSecret" . }}
  labels:
  {{ include "matrix.labels" . | nindent 4}}
stringData:
  registration.yaml: |-
    id: appservice-hookshot
    as_token: "{{ include "matrix.hookshot.as_token" . }}"
    hs_token: "{{ include "matrix.hookshot.hs_token" . }}"
    namespaces:
      users:
        - exclusive: true
          regex: "@webook_.+:{{ .Values.matrix.serverName }}"
    url: "http://{{ include "matrix.fullname" . }}-bridge-hookshot:{{ .Values.bridges.hookshot.service.port }}"
    sender_localpart: _hookshot_bot
    rate_limited: false
    protocols:
      - hookshot
{{- end }}
