{{- if .Values.bridges.hookshot.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "matrix.fullname" . }}-bridge-hookshot
  labels:
{{ include "matrix.labels" . | indent 4 }}
spec:
  type: {{ .Values.bridges.hookshot.service.type }}
  ports:
    - port: {{ .Values.bridges.hookshot.config.bridge.port }}
      targetPort: bridge
      protocol: TCP
      name: bridge
    - port: {{ .Values.bridges.hookshot.service.webhook.port }}
      targetPort: webhook
      protocol: TCP
      name: webhook
    - port: {{ .Values.bridges.hookshot.service.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: {{ .Values.bridges.hookshot.service.appservice.port }}
      targetPort: appservice
      protocol: TCP
      name: appservice
  selector:
    app.kubernetes.io/name: {{ include "matrix.name" . }}-bridge-hookshot
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
