{{- if and (not .Values.bridges.rss.existingSecret.config ) .Values.bridges.rss.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matrix.rss.configSecret" . }}
  labels:
  {{ include "matrix.labels" . | nindent 4}}
stringData:
  config.yml: |
    {{- include "rss_config.yml" . | nindent 4 }}
{{- end }}
