{{- if .Values.synapse.ingress.enabled }}
{{- $svcPort := .Values.synapse.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "matrix.fullname" . }}-synapse
  labels:
    {{- include "matrix.labels" . | nindent 4 }}
  {{- with .Values.synapse.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.synapse.ingress.className }}
  ingressClassName: {{ .Values.synapse.ingress.className }}
  {{- end }}
  rules:
    {{- if .Values.synapse.ingress.host }}
    - host: {{ .Values.synapse.ingress.host }}
      http:
        paths:
          - path: "/"
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "matrix.fullname" . }}-synapse
                port:
                  number: {{ $svcPort }}
    {{- else -}}
    {{- range .Values.synapse.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              {{- if hasKey . "backend" }}{{/* if user has provided a backend for path */}}
              {{- with .backend }}
              {{- toYaml . | nindent 15 }}
              {{- end }}
              {{- else -}}{{/* else we template out a service backend */}}
              service:
                name: {{ include "matrix.fullname" . }}-synapse
                port:
                  number: {{ $svcPort }}
              {{- end }}{{/* end checking for backend key */}}
          {{- end }}{{/* end range paths */}}
    {{- end }}{{/* end range hosts */}}
    {{- end }}{{/* end if old host method of ingress from old chart */}}
{{- if .Values.synapse.ingress.tls.enabled }}
  tls:
    - secretName: {{ .Values.synapse.ingress.tls.secretName }}
      hosts:
        - {{ .Values.synapse.ingress.host }}
{{- end }}
{{- end }}
