{{- if .Values.synapse.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "matrix.fullname" . }}-synapse
  labels:
    {{- include "matrix.labels" . | nindent 4 }}
  {{- with .Values.synapse.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.synapse.ingress.className }}
  ingressClassName: {{ .Values.synapse.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.synapse.ingress.host }}
      http:
        paths:
          - path: "/"
            pathType: ImplementationSpecific
            backend:
              service:
                name: "{{ include "matrix.fullname" . }}-synapse"
                port:
                  number: {{ .Values.synapse.service.port }}

          {{- if .Values.mas.enabled }}
          - path: "/_matrix/client/(r0|v3)/(refresh|login|logout).*"
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ template "mas.fullname" .Subcharts.mas }}
                port:
                  number: {{ .Values.mas.service.port }}
          {{- end }}
{{- if .Values.synapse.ingress.tls.enabled }}
  tls:
    - secretName: {{ .Values.synapse.ingress.tls.secretName }}
      hosts:
        - {{ .Values.synapse.ingress.host }}
{{- end }}
{{- end }}
