{{- if .Values.synapse.ingress.enabled }}
{{- $svcPort := .Values.synapse.service.port -}}
{{- $fullname := printf "%s-synapse" (include "matrix.fullname" .) -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "matrix.labels" . | nindent 4 }}
  {{- with .Values.synapse.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.synapse.ingress.className }}
  ingressClassName: {{ .Values.synapse.ingress.className }}
  {{- end }}
  rules:
  {{- if .Values.synapse.ingress.host }}{{/* this method will be deprecated in the future */}}
    - host: {{ .Values.synapse.ingress.host }}
      http:
        paths:
          - path: "/"
            {{- if .Values.mas.enabled }}
            pathType: Prefix
            {{- else }}
            pathType: ImplementationSpecific
            {{- end }}
            backend:
              service:
                name: {{ $fullname }}
                port:
                  number: {{ $svcPort }}
          {{- if .Values.mas.enabled }}
          - path: "/_matrix/client/(r0|v3)/(refresh|login|logout).*"
            pathType: ImplementationSpecific
            backend:
              service:
                value: {{ template "matrix-authentication-service.fullname" .Subcharts.mas }}
                port:
                  name: http
          {{- end }}{{/* end if mas is enabled */}}
  {{- else -}}
    {{- range .Values.synapse.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType }}
            backend:
              {{- if hasKey . "backend" }}{{/* if user has provided a backend for path */}}
              {{- with .backend }}
              {{- toYaml . | nindent 15 }}
              {{- end }}
              {{- else -}}{{/* else we template out a service backend */}}
              service:
                name: {{ $fullname }}
                port:
                  number: {{ $svcPort }}
              {{- end }}{{/* end checking for backend key */}}
          {{- end }}{{/* end range paths */}}
    {{- end }}{{/* end range hosts */}}
  {{- end }}{{/* end if old host method of ingress from old chart */}}
  {{- with .Values.synapse.ingress.tls }}
  tls:
    {{- range . }}
    - secretName: {{ .secretName }}
      hosts:
        {{- range .hosts }}
        - {{ . }}
        {{- end }}
    {{- end }}{{/* end range of tls list items */}}
  {{- end }}{{/* end with .Values.synapse.tls */}}
{{- end }}{{/* end if synapse.ingress.enabled */}}
