{{- if .Values.bridges.discord_mautrix.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "matrix.fullname" . }}-bridge-discord
  labels:
{{ include "matrix.labels" . | indent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "matrix.name" . }}-bridge-discord
      app.kubernetes.io/instance: {{ .Release.Name }}
      matrix-chart/allow-synapse-access: allow
  template:
    metadata:
      annotations:
        # re-roll deployment on config change
        checksum/discord-config: {{ include (print $.Template.BasePath "/bridge-mautrix-discord/secret-config.yaml") . | sha256sum }}
        checksum/discord-registration: {{ include (print $.Template.BasePath "/bridge-mautrix-discord/secret-registration.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "matrix.name" . }}-bridge-discord
        app.kubernetes.io/instance: {{ .Release.Name }}
        matrix-chart/allow-synapse-access: allow
    spec:
      {{- if .Values.bridges.affinity }}
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - {{ include "matrix.name" . }}-synapse
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - {{ .Release.Name }}
              topologyKey: kubernetes.io/hostname
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.bridges.discord_mautrix.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: "load-config"
          image: "{{ .Values.bridges.discord_mautrix.image.repository }}:{{ .Values.bridges.discord_mautrix.image.tag }}"
          imagePullPolicy: {{ .Values.bridges.discord_mautrix.image.pullPolicy }}
          command: ["sh"]
          args: ["-c", "cp /load/registration.yaml /bridges/discord.yaml && cp /load/registration.yaml /data/registration.yaml && cp /load/config.yaml /data/config.yaml"]
          volumeMounts:
            - name: load
              mountPath: /load
            - name: data
              mountPath: /data
            - name: bridges
              mountPath: /bridges
          {{- with .Values.bridges.discord_mautrix.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      containers:
        - name: "bridge-discord"
          image: "{{ .Values.bridges.discord_mautrix.image.repository }}:{{ .Values.bridges.discord_mautrix.image.tag }}"
          imagePullPolicy: {{ .Values.bridges.discord_mautrix.image.pullPolicy }}
          ports:
            - name: bridge
              containerPort: {{ .Values.bridges.discord_mautrix.config.appservice.port }}
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
           {{- with .Values.bridges.discord_mautrix.extraVolumeMounts }}
             {{- toYaml . | nindent 12 }}
           {{- end }}
          {{- with .Values.bridges.discord_mautrix.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.bridges.discord_mautrix.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: load
          projected:
            sources:
              - secret:
                  name: {{ include "matrix.discord_mautrix.configSecret" . }}
              - secret:
                  name: {{ include "matrix.discord_mautrix.registrationSecret" . }}
        - name: bridges
          persistentVolumeClaim:
            {{- if not .Values.bridges.volume.existingClaim }}
            claimName: "{{ include "matrix.fullname" . }}-bridges"
            {{- else -}}
            claimName: {{ .Values.bridges.volume.existingClaim }}
            {{- end }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "matrix.discord_mautrix.pvc" . }}
        {{- with .Values.bridges.discord_mautrix.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
