name: Lint, Test, Document Chart

on:
  pull_request:
    paths:
      - 'charts/matrix/**'

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Install Helm
        uses: azure/setup-helm@v3.5

      - name: Add dependency chart repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add coturn https://jessebot.github.io/coturn-chart

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        id: lint
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        id: install
        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --target-branch ${{ github.event.repository.default_branch }}

      # update the docs
      - uses: gabe565/setup-helm-docs-action@v1
      - name: generate helm docs with helm-docs
        run: helm-docs
      - name: commit helm docs changes

      # commit the docs changes back up
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'charts/matrix/README.md'
          author_name: jessebot
          committer_name: friend
          message: 'Automated GHA - Updating helm docs'
